In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import scipy.stats as stats

In [2]:
d1=pd.read_csv('C:\\Users\\Yash\\Desktop\\STATS\\CASE STUDY FOR PANDAS\\7. Basic Stats - Case Study-1\\dietstudy.csv')
d2=pd.read_csv('C:\\Users\\Yash\\Desktop\\STATS\\CASE STUDY FOR PANDAS\\7. Basic Stats - Case Study-1\\creditpromo.csv')
d3=pd.read_csv('C:\\Users\\Yash\\Desktop\\STATS\\CASE STUDY FOR PANDAS\\7. Basic Stats - Case Study-1\\pollination.csv')
d4=pd.read_csv('C:\\Users\\Yash\\Desktop\\STATS\\CASE STUDY FOR PANDAS\\7. Basic Stats - Case Study-1\\dvdplayer.csv')
d5=pd.read_csv('C:\\Users\\Yash\\Desktop\\STATS\\CASE STUDY FOR PANDAS\\7. Basic Stats - Case Study-1\\sample_survey.csv')


In [3]:
d1.head()

patid  age  gender  tg0  tg1  tg2  tg3  tg4  wgt0  wgt1  wgt2  wgt3  wgt4
0      1   45    Male  180  148  106  113  100   198   196   193   188   192
1      2   56    Male  139   94  119   75   92   237   233   232   228   225
2      3   50    Male  152  185   86  149  118   233   231   229   228   226
3      4   46  Female  112  145  136  149   82   179   181   177   174   172
4      5   64    Male  156  104  157   79   97   219   217   215   213   214

In [4]:
#Q1...... T-Test
pr1=d1.groupby(['tg0','tg4']).size().reset_index().describe()
pr2=d1.groupby(['wgt0','wgt4']).size().reset_index().describe()
print(pr1)
print(pr2)

             tg0         tg4     0
count   16.00000   16.000000  16.0
mean   138.43750  124.375000   1.0
std     29.04013   29.411732   0.0
min     94.00000   82.000000   1.0
25%    110.75000   99.250000   1.0
50%    142.00000  122.000000   1.0
75%    157.00000  148.500000   1.0
max    186.00000  174.000000   1.0
             wgt0        wgt4          0
count   15.000000   15.000000  15.000000
mean   196.066667  187.933333   1.066667
std     33.302653   33.255433   0.258199
min    151.000000  140.000000   1.000000
25%    168.000000  161.000000   1.000000
50%    198.000000  192.000000   1.000000
75%    220.500000  212.000000   1.000000
max    257.000000  249.000000   2.000000


In [5]:
pr1.sem()

tg0    21.321946
tg4    19.487710
0       1.896896
dtype: float64

In [6]:
pr2.sem()

wgt0    30.713191
wgt4    29.553583
0        1.752063
dtype: float64

In [7]:
#triglyceride levels of patients
d1.tg0.mean()

138.4375

In [8]:
#final triglyceride levels of patients
d1.tg4.mean()

124.375

In [9]:
#weights of pateints
d1.wgt0.mean()

198.375

In [10]:
#final weights of pateints
d1.wgt4.mean()

190.3125

In [11]:
#FInal wieght and inital weight difreenece
d1.wgt0.mean()-d1.wgt4.mean()

8.0625

In [12]:
#1
#H0: levels of Triglycerides  before diet are equal levels of Triglycerides  after diet
#H1: levels of Triglycerides  before diet are not equal levels of Triglycerides after diet

stat1 = stats.ttest_rel(a=d1.tg0,b=d1.tg4) 

In [13]:
stat1.pvalue

0.24874946576903698

In [14]:
stat1.pvalue>0.05

True

In [15]:
#2
#H0: weights of individual before diet are equal  weights of individual after diet
#H1: weights of individual before diet are not equal  weights of individual after diet

In [16]:
stat2 = stats.ttest_rel(a=d1.wgt0,b=d1.wgt4) 

In [17]:
stat2.pvalue

1.137689414996614e-08

In [18]:
stat2.pvalue>0.05

False

In [19]:
# p-value in weight < 0.05
# we can say that 8.0625 wight is not loss due to variation 
# p-value greater > 0.05 in triglyceride shows diet did not  reduce their triglyceride levels

In [20]:
#Q2

d2['type']=d2['insert']

d2['type'].replace(0, 'Standard',inplace=True)

d2


id         insert      dollars           type
0       148       Standard  2232.771979       Standard
1       572  New Promotion  1403.807542  New Promotion
2       973       Standard  2327.092181       Standard
3      1096       Standard  1280.030541       Standard
4      1541  New Promotion  1513.563200  New Promotion
..      ...            ...          ...            ...
495  130163  New Promotion  1513.060134  New Promotion
496  130204  New Promotion  1020.757943  New Promotion
497  130255       Standard  1919.856304       Standard
498  130583       Standard  1863.014814       Standard
499  130682       Standard  1295.012183       Standard

[500 rows x 4 columns]

In [21]:
spent_during_promotional_period = d2['dollars'].loc[d2['insert']=="Standard"]

Type_of_mail_insert = d2['dollars'].loc[d2['insert']=="New Promotion"]

In [22]:
print (spent_during_promotional_period.mean())
print (Type_of_mail_insert.mean())

1566.3890309659348
1637.4999830647992


In [23]:
print (spent_during_promotional_period.var())
print (Type_of_mail_insert.var())

120182.20156769526
127237.15055227646


In [24]:
variance_equal = stats.ttest_ind(a= spent_during_promotional_period,b= Type_of_mail_insert,equal_var=True)  
variance_equal.statistic

-2.2604227264649963

In [25]:
variance_unequal = stats.ttest_ind(a=spent_during_promotional_period,b= Type_of_mail_insert,equal_var=False)
variance_unequal.statistic


-2.260422726464996

In [26]:
variance_unequal.statistic-variance_equal.statistic

4.440892098500626e-16

In [27]:

truth = variance_equal.statistic

fals = variance_equal.pvalue

print("  t-score -{}\n p-value -{}".format(truth,fals))

if(fals<0.05):
    print('reject null hypothesis')
else:
    print('accept null hypothesis')

  t-score --2.2604227264649963
 p-value -0.024225996894147814
reject null hypothesis


In [28]:
#Q3----A
d3.head()

Group  Fruit_Wt  Seed_Yield_Plant  Seedling_length
0  Natural      1.85            147.70            16.86
1  Natural      1.86            136.86            16.77
2  Natural      1.83            149.97            16.35
3  Natural      1.89            172.33            18.26
4  Natural      1.80            144.46            17.90

In [29]:
#One Sample t-Test
#Ho- Population of Seed yield/plant equal 200 
#Ha - Population of Seed yield/plant not equal 200

In [30]:
d3.Seed_Yield_Plant.mean()

180.8035

In [31]:
testing = stats.ttest_1samp(a=d3.Seed_Yield_Plant, popmean = 200)
t_score = round(testing.statistic,3)
p_value = testing.pvalue
print("T Score - {} \n  p value- {} ".format(p_value,t_score))

T Score - 0.032891040921283025 
  p value- -2.301 


In [32]:
p_value>0.05 

False

In [33]:
#rejecting null hypothesis

In [34]:
#Q3-----B

#F-Test/Anova

#H0 -mean Fruit_Wt = mean Seed_Yield_Plant = mean Seedling_length

#H1-mean Fruit_Wt != mean Seed_Yield_Plant != mean Seedling_length

In [35]:
d3.head()

Group  Fruit_Wt  Seed_Yield_Plant  Seedling_length
0  Natural      1.85            147.70            16.86
1  Natural      1.86            136.86            16.77
2  Natural      1.83            149.97            16.35
3  Natural      1.89            172.33            18.26
4  Natural      1.80            144.46            17.90

In [36]:
natural_pollination = d3['Fruit_Wt'].loc[d3['Group']=="Natural"]
hand_pollination = d3['Fruit_Wt'].loc[d3['Group']=="Hand"]

anova = stats.f_oneway(natural_pollination,hand_pollination)



f_val_1 = anova.statistic
p_val_1 = anova.pvalue
print("f-value -{} \n p value- {}".format(f_val_1,p_val_1))

f-value -312.228532974426 
 p value- 8.078362076486568e-13


In [37]:
natural_seed_pollination = d3['Seed_Yield_Plant'].loc[d3['Group']=="Natural"]
hand_seed_pollination = d3['Seed_Yield_Plant'].loc[d3['Group']=="Hand"]
anova = stats.f_oneway(natural_seed_pollination,hand_seed_pollination)



f_val_2 = anova.statistic
p_val_2 = anova.pvalue
print("f-value -{} \n p value- {}".format(f_val_2,p_val_2))

f-value -194.83303662980398 
 p value- 4.271481585484407e-11


In [38]:
natural_length_pollination = d3['Seedling_length'].loc[d3['Group']=="Natural"]
hand_length_pollination = d3['Seedling_length'].loc[d3['Group']=="Hand"]

anova = stats.f_oneway(natural_length_pollination,hand_length_pollination)



f_val_3 = anova.statistic
p_val_3 = anova.pvalue
print(" f-value -{} \n p value- {}".format(f_val_3,p_val_3))

 f-value -6.46293337115627 
 p value- 0.020428817064110556


In [39]:
#Q4
#F-Test/Anova
#H0-all mean of(agegroup-65 and over,55-64,Under 25 and 35-54 and 45-54 and 25-34) are equal
#Ha-all mean of(agegroup-65 and over,55-64,Under 25 and 35-54 and 45-54 and 25-34) are not equal

d4.head()

agegroup   dvdscore
0  65 and over  38.454803
1        55-64  17.669677
2  65 and over  31.704307
3  65 and over  25.924460
4     Under 25  30.450007

In [40]:
agegroup_1 = d4['dvdscore'].loc[d4['agegroup']=="65 and over"]
agegroup_2 = d4['dvdscore'].loc[d4['agegroup']=="55-64"]
agegroup_3 = d4['dvdscore'].loc[d4['agegroup']=="Under 25"]
agegroup_4 = d4['dvdscore'].loc[d4['agegroup']=="35-44"]
agegroup_5 = d4['dvdscore'].loc[d4['agegroup']=="45-54"]
agegroup_6 = d4['dvdscore'].loc[d4['agegroup']=="25-34"]


anova_test = stats.f_oneway(agegroup_1,agegroup_2,agegroup_3,agegroup_4,agegroup_5,agegroup_6)

f = anova_test.statistic
p = anova_test.pvalue


print("f-value - {} \n p value is {}".format(f,p))
if(p<0.05):
    print('rejecting null hypothesis')
else:
    print('accepting null hypothesis')

f-value - 6.992526962676517 
 p value is 3.087324905679639e-05
rejecting null hypothesis


In [41]:
#Q5-----A
# Chi-Square Test
# H0 :No relation between labour force status and marital status

# Ha :realtionship between labour force status and marital status

In [42]:
d5.head()

id            wrkstat        marital  childs   age  educ  paeduc  maeduc  \
0   1  Working full time       Divorced     2.0  60.0  12.0    12.0    12.0   
1   2  Working part-time  Never married     0.0  27.0  17.0    20.0     NaN   
2   3  Working full time        Married     2.0  36.0  12.0    12.0    12.0   
3   4  Working full time  Never married     0.0  21.0  13.0     NaN    12.0   
4   5  Working full time  Never married     0.0  35.0  16.0     NaN    12.0   

   speduc          degree  ...        agecat childcat news1 news2  news3  \
0     NaN     High school  ...      55 to 64      1-2    No    No     No   
1     NaN  Junior college  ...      25 to 34     None    No    No    Yes   
2    16.0     High school  ...      35 to 44      1-2    No    No     No   
3     NaN     High school  ...  Less than 25     None    No    No     No   
4     NaN        Bachelor  ...      35 to 44     None    No    No     No   

  news4 news5      car1      car2      car3  
0    No    No  American  Japanese  Japanese  
1    No    No  American    German  Japanese  
2   Yes   Yes  American  American       NaN  
3   Yes   Yes  American     Other       NaN  
4    No    No  American  American    Korean  

[5 rows x 46 columns]

In [43]:
sample_survey = pd.crosstab(d5.wrkstat, d5.marital, margins = True)
sample_survey

marital                  Divorced  Married  Never married  Separated  Widowed  \
wrkstat                                                                         
Keeping house                  25      200             35         13       55   
Other                          12       16             14          4        8   
Retired                        53      168             17          6      150   
School                          7        9             60          2        1   
Temporarily not working         9       23             11          1        2   
Unemployed, laid off           10       13             32          0        3   
Working full time             295      778            392         58       44   
Working part-time              35      138            102          9       20   
All                           446     1345            663         93      283   

marital                   All  
wrkstat                        
Keeping house             328  
Other                      54  
Retired                   394  
School                     79  
Temporarily not working    46  
Unemployed, laid off       58  
Working full time        1567  
Working part-time         304  
All                      2830

In [44]:

sample_survey_test = stats.chi2_contingency(observed= sample_survey)

sample_survey_test

(729.2421426572284,
 1.820339965538765e-127,
 40,
 array([[5.16918728e+01, 1.55886926e+02, 7.68424028e+01, 1.07787986e+01,
         3.28000000e+01, 3.28000000e+02],
        [8.51024735e+00, 2.56643110e+01, 1.26508834e+01, 1.77455830e+00,
         5.40000000e+00, 5.40000000e+01],
        [6.20932862e+01, 1.87254417e+02, 9.23045936e+01, 1.29477032e+01,
         3.94000000e+01, 3.94000000e+02],
        [1.24501767e+01, 3.75459364e+01, 1.85077739e+01, 2.59611307e+00,
         7.90000000e+00, 7.90000000e+01],
        [7.24946996e+00, 2.18621908e+01, 1.07766784e+01, 1.51166078e+00,
         4.60000000e+00, 4.60000000e+01],
        [9.14063604e+00, 2.75653710e+01, 1.35879859e+01, 1.90600707e+00,
         5.80000000e+00, 5.80000000e+01],
        [2.46954770e+02, 7.44740283e+02, 3.67109894e+02, 5.14950530e+01,
         1.56700000e+02, 1.56700000e+03],
        [4.79095406e+01, 1.44480565e+02, 7.12197880e+01, 9.99010601e+00,
         3.04000000e+01, 3.04000000e+02],
        [4.46000000e+02, 1.345

In [45]:
print("chi square- {} \n p value is {}".format(sample_survey_test[0],sample_survey_test[1]))
if(p<0.05):
    print('rejecting null hypothesis')
else:
    print('accepting null hypothesis')

chi square- 729.2421426572284 
 p value is 1.820339965538765e-127
rejecting null hypothesis


In [46]:
#Q5-----B
#Chi- Square Test
#H0 - No relation between educational qualification and marital status

#Ha - realtionship between educational qualification and marital status

In [47]:
sample_survey_1 = pd.crosstab(d5.degree, d5.marital, margins = True)
sample_survey_1

marital         Divorced  Married  Never married  Separated  Widowed   All
degree                                                                    
Bachelor              58      251            129         12       28   478
Graduate              29      123             41          3        9   205
High school          241      686            367         58      148  1500
Junior college        45      108             46          3        6   208
LT High school        70      174             77         17       92   430
All                  443     1342            660         93      283  2821

In [48]:
sample_survey_test_1 = stats.chi2_contingency(observed= sample_survey_1)

sample_survey_test_1


(122.68449020508541,
 7.424404099753273e-15,
 25,
 array([[  75.06345268,  227.39312301,  111.83268345,   15.75824176,
           47.95249911,  478.        ],
        [  32.19248493,   97.52215526,   47.9617157 ,    6.75824176,
           20.56540234,  205.        ],
        [ 235.55476781,  713.57674583,  350.9393832 ,   49.45054945,
          150.4785537 , 1500.        ],
        [  32.66359447,   98.94930876,   48.66359447,    6.85714286,
           20.86635945,  208.        ],
        [  67.52570011,  204.55866714,  100.60262318,   14.17582418,
           43.1371854 ,  430.        ],
        [ 443.        , 1342.        ,  660.        ,   93.        ,
          283.        , 2821.        ]]))

In [49]:

print("chi square- {} \n p value is {}".format(sample_survey_test_1[0],sample_survey_test_1[1]))
if(p<0.05):
    print('rejecting null hypothesis')
else:
    print('accepting null hypothesis')

chi square- 122.68449020508541 
 p value is 7.424404099753273e-15
rejecting null hypothesis


In [50]:
#Q5-----C
#Chi- Square Test
#H0 -No relation between happiness by earnings and marital status

#Ha -realtionship between happiness by earnings and marital status
 

In [51]:
sample_survey_2 = pd.crosstab(d5.happy, d5.income, margins = True)
sample_survey_2

income         $1000 TO 2999  $10000 - 14999  $15000 - 19999  $20000 - 24999  \
happy                                                                          
Not too happy              7              39              33              40   
Pretty happy              20             107             119             155   
Very happy                 5              44              26              50   
All                       32             190             178             245   

income         $25000 or more  $3000 TO 3999  $4000 TO 4999  $5000 TO 5999  \
happy                                                                        
Not too happy             113              9              9              6   
Pretty happy              888             11             13             18   
Very happy                571              4             10             11   
All                      1572             24             32             35   

income         $6000 TO 6999  $7000 TO 7999  $8000 TO 9999  LT $1000   All  
happy                                                                       
Not too happy             14             12              9        11   302  
Pretty happy              13             21             30        13  1408  
Very happy                 6             14             19        11   771  
All                       33             47             58        35  2481

In [52]:

sample_survey_test_2 = stats.chi2_contingency(observed= sample_survey_2)

sample_survey_test_2

(178.95053061216427,
 7.234749067043371e-21,
 36,
 array([[   3.89520355,   23.12777106,   21.66706973,   29.82265216,
          191.35187424,    2.92140266,    3.89520355,    4.26037888,
            4.01692866,    5.72108021,    7.06005643,    4.26037888,
          302.        ],
        [  18.16041919,  107.82748892,  101.01733172,  139.04070939,
          892.1305925 ,   13.62031439,   18.16041919,   19.86295848,
           18.72793229,   26.67311568,   32.91575977,   19.86295848,
         1408.        ],
        [   9.94437727,   59.04474002,   55.31559855,   76.13663845,
          488.51753325,    7.45828295,    9.94437727,   10.87666264,
           10.25513906,   14.60580411,   18.0241838 ,   10.87666264,
          771.        ],
        [  32.        ,  190.        ,  178.        ,  245.        ,
         1572.        ,   24.        ,   32.        ,   35.        ,
           33.        ,   47.        ,   58.        ,   35.        ,
         2481.        ]]))

In [53]:

print("chi square - {} \n p value - {}".format(sample_survey_test_2[0],sample_survey_test_2[1]))

chi square - 178.95053061216427 
 p value - 7.234749067043371e-21


In [54]:

sample_survey_3 = pd.crosstab(d5.happy, d5.marital, margins = True)
sample_survey_3

marital        Divorced  Married  Never married  Separated  Widowed   All
happy                                                                    
Not too happy        72       71            108         30       59   340
Pretty happy        278      684            426         49      137  1574
Very happy           93      582            120         13       83   891
All                 443     1337            654         92      279  2805

In [55]:
sample_survey_test_3 = stats.chi2_contingency(observed= sample_survey_3)

sample_survey_test_3

(260.68943894182826,
 7.762777322980048e-47,
 15,
 array([[  53.6969697 ,  162.06060606,   79.27272727,   11.15151515,
           33.81818182,  340.        ],
        [ 248.58538324,  750.24527629,  366.98609626,   51.62495544,
          156.55828877, 1574.        ],
        [ 140.71764706,  424.69411765,  207.74117647,   29.22352941,
           88.62352941,  891.        ],
        [ 443.        , 1337.        ,  654.        ,   92.        ,
          279.        , 2805.        ]]))

In [56]:

print("chi square- {} \n p value is {}".format(sample_survey_test_3[0],sample_survey_test_3[1]))
if(p<0.05):
    print('rejecting null hypothesis')
else:
    print('accepting null hypothesis')
    
print('here  260.68 is more than 178.95 so happiness is driven by marital status')

chi square- 260.68943894182826 
 p value is 7.762777322980048e-47
rejecting null hypothesis
here  260.68 is more than 178.95 so happiness is driven by marital status
